name: pathCompleter
description: A package to complete paths.
version: 0.0.1
author: Ravi Teja Gudapati <tejainece@gmail.com>
homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  path: "^1.3.9"

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
